name: kiblat
description: "App to find the Qibla direction"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  flutter_localizations:
    sdk: flutter
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  flutter_compass: ^0.8.1
  google_maps_flutter: ^2.2.0
  google_mobile_ads: ^5.3.0
  url_launcher: ^6.1.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/translations/
